### ISSUE TITLE
Licznik dodanych urządzeń ;-)

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/aed-mapa#16]
Co wy na to? gdzieś na pasku, a jeszcze lepiej jakieś statystyki?

**Comment by matkoniecz** [comment]
chyba jest dodany?

**Comment by Ancymonek** [comment]
Dodane, w branchu developement jest nowa zmiana pobierająca te dane z pliku json, a nie jak poprzednio zliczająca obiekty w geojson.
