### ISSUE TITLE
clustering broken (clustered, not shown as clustered)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/aed-mapa#21]
https://aed.openstreetmap.org.pl/#map=15.96/50.068044/19.945995

![screen02](https://user-images.githubusercontent.com/899988/146528336-95695b79-61da-458a-a893-4e627d8112c3.png)

https://aed.openstreetmap.org.pl/#map=16.84/50.067948/19.947142

![screen03](https://user-images.githubusercontent.com/899988/146528353-99f0e614-4816-4316-9902-26154b4bd593.png)

**Comment by ttomasz** [comment]
to chyba kwestia że domyślnie nie pozwala na overlapping ikon, a jednocześnie może być minimalne niedogranie między zasięgiem klastrowania, a wielkością ikony
