### ISSUE TITLE
"Ostatnia aktualizacja" - brzmi jak data edycji, nie importu

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/aed-mapa#24]
![unknown](https://user-images.githubusercontent.com/899988/146907473-418b31e6-8c30-479e-9486-c2cb9dad9fbe.png)

Co byłoby lepsze?

"Synchronizacja z bazą OSM" "Skopiowanie danych z OSM" "zmiany nowsze niż X minut nie są widoczne" "jeśli wyedytowałeś ten obiekt mniej niż X minut temu to nie jest to jeszcze widoczne"?

"import" byłby raczej niejasny

**Comment by mutipg** [comment]
Zasadniczo to co teraz jest wyświetlane nie jest złe.

Problemem wg mnie jest tylko to, że ten komunikat pojawia się po kliknięciu w punkt razem z informacjami dotyczącymi klikniętego AED.

Taka informacja mogłaby być stale wyświetlana np. przy atrybucji mapy i problem byłby rozwiązany.

**Comment by Ancymonek** [comment]
Wrzuciłem do atrubucji (po najechaniu na 'X minut temu' pokazuje się tooltip z datą, do podglądu na https://aed.openstreetmap.org.pl/dev/#map=6/52.068/16.049

**Comment by mutipg** [comment]
Świetna robota. Teraz nikt się nie powinien pomylić czego dotyczy ten opis.

**Comment by Ancymonek** [comment]
PS rozwiązanie trzeba dopracować, bo nie wyświetla się za każdym razem.

**Comment by ttomasz** [comment]
> PS rozwiązanie trzeba dopracować, bo nie wyświetla się za każdym razem.

Zmieniłem na devie na odpalenie funkcji po załadowaniu mapy, wtedy nie powinno być problemu że nie może uzupełnic obiektu w atrybucji.
