### ISSUE TITLE
Zmiana położenia przycisku do dodawania

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap-polska/aed-mapa#34]
Ja go nie znalazłem... może prawy górny róg? albo ta belka zielona??

**Comment by ttomasz** [comment]
wrzucisz screena jak to u ciebie wygląda?

**Comment by ttomasz** [comment]
przycisk po zmianach powinien być bardziej widoczny mimo że dalej jest w lewym dolnym rogu
