### ISSUE TITLE
Pobieranie danych w xls pliku

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/aed-mapa#37]
Najlepiej by od razu stworzyć tłumacz, który ułatwia czytanie osobom niezwiązanym z osm w tym zamiast osm_id link do obiektu

**Comment by ttomasz** [comment]
rozpoczęte w 3960939b28d4f2c2ead3956e18a23b186c00f9d0

**Comment by ttomasz** [comment]
https://aed.openstreetmap.org.pl/aed_poland.ods
