### ISSUE TITLE
Przycisk dodawania nie zmienia przezroczystości przy zmianie przybliżenia

### ISSUE THREAD

**Issue by miklobit** [openstreetmap-polska/aed-mapa#42]
Problem dotyczy Firefox (v.95) na Android  
Podczas przybliżania mapy przycisk dodawania nie zmienia przezroczystości i nie wiadomo czy już jest poziom przybliżenia na ktorym dodawanie działa.
Na  desktopie ta zmiana tez jest zresztą dosyć mało widoczna. 
Może zamiast przezroczystości przycisku (albo dodatkowo)  zmieniać jego kolor np z żółtego na zielony ?

**Comment by ttomasz** [comment]
1a36e6d78ab54fcedfec93f18b0a161e75ccd1f3

**Comment by ttomasz** [comment]
wrzucone na prod, cache wygasa po 24h, więc możliwe, że żeby zobaczyć wcześniej trzeba wyczyścić dane przeglądania (ctrl+f5 na desktop)
