### ISSUE TITLE
indoor=* vs location=*

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/aed-mapa#44]
https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator zaleca `indoor=*` a nie `location=*`

https://taginfo.openstreetmap.org/tags/emergency=defibrillator#combinations potwierdza

**Comment by ttomasz** [comment]
Tagi na wiki są do uporządkowania, bo obecnie to ten indoor jest niespójny, access jest dodawany jak komu się podoba, a opis lokalizacji to w ogóle masakra jest chyba 6 różnych tagów stosowanych w praktyce.

Zmiany na stronie będą po ogarnięciu tego po stronie OSM.

**Comment by matkoniecz** [comment]
`indoor=` akurat jest dość systematycznie stosowany, to polskie `location=*` jest nietypowe

**Comment by Ancymonek** [comment]
Dla uspójnienia: zmiana  indoor=* na location=* wzięła się z dyskusji na Discordzie

**Comment by matkoniecz** [comment]
Dasz linka do dyskusji? Lub podasz jakie argumenty za tym były?

Bo to jest jakieś lokalne polskie dziwactwo bez uzasadnienia na razie

**Comment by Ancymonek** [comment]
Zaczęło się tu: https://discord.com/channels/783754873861963786/918900705182511145/920647244053639238 później się raczej przewijało gdzieś między wierszami kilka razy

**Comment by wzbartczak** [comment]
Zobaczcie schemat oznaczania AED

indoor = yes/no praktycznie wyłacznie
location = nie ma
defibrillator:location = opis

wiki zostało poprawione

**Comment by matkoniecz** [comment]
>Zaczęło się tu: https://discord.com/channels/783754873861963786/918900705182511145/920647244053639238 później się raczej przewijało gdzieś między wierszami kilka razy

Z tego co widziałem to w tej dyskusji przegapione zostało (w tym przeze mnie) że `indoor=yes/no` to standard
