### ISSUE TITLE
Wskazać użytkownikowi, że marker może zostać przesunięty

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap-polska/aed-mapa#46]
Było kilka edycji, gdzie ewidentnie dodający nie wiedział, że marker można przesunąć. Trzeba to jakoś uwydatnić w interfejsie.

**Comment by ksciana** [comment]
Używana biblioteka do obsługi m.in. markerów pozwala na dodanie popup-a: https://maplibre.org/maplibre-gl-js-docs/api/markers/#marker#setpopup

Wystarczy w czasie budowania markera, dodać do niego taki popup z informacją, że można go przesuwać po mapie.
Po dodaniu go do mapy wystarczy potem po pokazać.

```JS
marker = new maplibregl.Marker({
            draggable: true,
            color: "#e81224",
        })
        .setLngLat(initialCoordinates);
//add popup
marker.setPopup(new maplibregl.Popup().setHTML("Przesuń marker w docelowe miejsce"))
marker.addTo(map);
//show popup
marker.togglePopup();

```

Poniżej jak to mogło by wyglądać, oczywiście trzeba popracować na stylem CSS.

mobile:
![image](https://user-images.githubusercontent.com/1391147/150653410-31df4979-00b7-462e-a845-d8040b0c91aa.png)

desktop:
![image](https://user-images.githubusercontent.com/1391147/150653453-1a82da6f-7a31-4737-9753-1f9d99cd2bbc.png)
