### ISSUE TITLE
Reskalowanie kafelków mapy

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap-polska/aed-mapa#59]
Siema. Jak mogę ponarzekać to włącza się Wam jakieś reskalowanie kafli... kiedyś coś takiego miałem i chyba wynikało to z innego rozmiaru niż 100% w css... alboco. W wyniku tego kafelki są lekko rozmyte. Problem występuje tutaj ale również na budynkach. Porównanie naszej mapy z OSM:

![obraz](https://user-images.githubusercontent.com/9802737/153098152-3c7cecc2-3d76-4d8d-b534-338c5ab73e9b.png)

**Comment by jendrusk** [comment]
yyy... albo nie? Leaflett pozwala na niepełne zoomlevele i z tego wynika rozmycie. Jak ustawię ZL na pełny to jest ostro...
Możnaby się zastanowić czy nie wymusić pełnych, ale to już od Was zależy - jak uznacie za niepotrzebne możecie śmiało zamknąć issue

**Comment by Ancymonek** [comment]
Też mi się to nie podoba, problem generuje linijka:

`map.scrollZoom.setWheelZoomRate(1 / 100);`
w map.js

Pomaga zmiana na:
`map.scrollZoom.setWheelZoomRate(1);`

@ttomasz, jest jakieś uzasadnienie na to 1/100?

**Comment by Ancymonek** [comment]
@jendrusk 
Na /dev dostępna jest wersja ze zmienionymi kafelkami:
https://aed.openstreetmap.org.pl/dev/

**Comment by Ancymonek** [comment]
Wersja wdrożona na /main, zamykam.
