### ISSUE TITLE
Pobieranie danych

### ISSUE THREAD

**Issue by wzbartczak** [openstreetmap-polska/aed-mapa#6]
Trzeba by się zastanowić jak i w jakim formacie umożliwić pobieranie danych shp, cvs oraz geopackege by wypadało ... no i jak często aktualizację zapuścić może na początku raz na 2 tyg?

**Comment by ttomasz** [comment]
dodany eksport csv do skryptu, powinno się odświeżać co godzinę
https://aed.openstreetmap.org.pl/aed_poland.geojson
https://aed.openstreetmap.org.pl/aed_poland.csv

**Comment by vilkh3m** [comment]
> dodany eksport csv do skryptu, powinno się odświeżać co godzinę https://aed.openstreetmap.org.pl/aed_poland.geojson https://aed.openstreetmap.org.pl/aed_poland.csv

Coś chyba nie działa, adres zwraca "502 Bad Gateway"

**Comment by ttomasz** [comment]
Był problem z serwerem przez kilka dni, teraz już wróciło do normy i można pobierać.
