### ISSUE TITLE
Usunięcie przycisku i warstwy 'Włącz/wyłącz warstwę AED mobilnych'

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/aed-mapa#64]
Chyba czas usunąć przycisk 'Włącz/wyłącz warstwę AED mobilnych' - po wprowadzeniu mobilnych AED do OSM te żółte kółeczka są mylące.
![image](https://user-images.githubusercontent.com/10333015/155497651-5ce0e6ad-59b3-4c27-bcb8-ad5766d6caf1.png)

**Comment by Ancymonek** [comment]
Zmienione, zmiany dostępne, póki co, na wersji /dev

**Comment by Ancymonek** [comment]
Jest już na /main - zamykam.
