### ISSUE TITLE
Licencja danych przy pobieraniu

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap-polska/aed-mapa#73]
Okienko pobierania danych powinno zawierać link do https://www.openstreetmap.org/copyright
np. z etykietą "Licencja danych".
(sama atrybucja już jest w rogu strony)

**Comment by Ancymonek** [comment]
Added. 

![obraz](https://user-images.githubusercontent.com/16021640/202166816-41a1bb49-866d-4ea2-9f8e-f3dec7d8ef82.png)
